# Generated by Django 5.1.7 on 2025-04-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=80)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.acessorio')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cor')),
            ],
        ),
    ]
